# Generated by Django 5.2 on 2025-05-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anbar', '0004_anbarrequestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='محصول')),
                ('unit', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'محصولات تولیدی',
                'verbose_name_plural': 'محصولات تولیدی',
            },
        ),
        migrations.CreateModel(
            name='ProductMaterialRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.FloatField(default=0.0, verbose_name='مقدار مواد اولیه برای تولید هر واحد از محصول')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.anbarmodel', verbose_name='مواد اولیه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='product.productmodel')),
            ],
            options={
                'verbose_name': 'رابط بین یک محصول نهایی و مواد اولیه',
                'verbose_name_plural': 'رابط بین یک محصول نهایی و مواد اولیه',
            },
        ),
    ]
