# Generated by Django 5.2 on 2025-05-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productmodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان هزینه')),
                ('monthly_cost', models.FloatField(verbose_name='هزینه ماهانه')),
            ],
            options={
                'verbose_name': 'هزینه ثابت',
                'verbose_name_plural': 'هزینه\u200cهای ثابت',
            },
        ),
    ]
