# Generated by Django 5.2 on 2025-07-19 17:34

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_alter_personelmodel_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان رمز')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=255, verbose_name='رمز عبور')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('create_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='user.personelmodel')),
            ],
        ),
    ]
