# Generated by Django 5.2 on 2025-05-21 13:33

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_productmodel_is_active'),
        ('user', '0006_destinationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnbarTolidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_inventory', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی کل')),
                ('remaining_inventory', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی باقی\u200cمانده')),
                ('create_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'انبار محصول',
                'verbose_name_plural': 'انبار محصول',
            },
        ),
        migrations.CreateModel(
            name='AnbarExitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار خروجی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('exit_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ خروج')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.destinationmodel', verbose_name='مشتری')),
                ('anbar_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.anbartolidmodel', verbose_name='کالای انبار')),
            ],
        ),
        migrations.CreateModel(
            name='TolidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی تولیدی')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد کالا')),
                ('is_export', models.CharField(choices=[('S', 'صادراتی'), ('D', 'داخلی')], max_length=1, verbose_name='صادراتی یا داخلی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('expiration_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انقضا ')),
                ('production_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولید ')),
                ('create_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel', verbose_name='کالای تولیدی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.personelmodel', verbose_name='تولید کننده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول',
            },
        ),
        migrations.AddField(
            model_name='anbartolidmodel',
            name='tolid_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.tolidmodel', verbose_name='محصول'),
        ),
    ]
