# Generated by Django 5.2 on 2025-05-26 18:33

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anbarexitmodel',
            options={'verbose_name': 'خروجی انبار محصول', 'verbose_name_plural': 'خروجی انبار محصول'},
        ),
        migrations.CreateModel(
            name='AnbarGhModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_inventory', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی کل')),
                ('start_date', django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='تاریخ ورود به انبار قرنطینه')),
                ('end_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ خروج به انبار قرنطینه')),
                ('create_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('tolid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.tolidmodel', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'انبار قرنطینه محصول',
                'verbose_name_plural': 'انبار قرنطینه محصول',
            },
        ),
    ]
