# Generated by Django 5.2 on 2025-05-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_anbarexitmodel_options_anbarghmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolidmodel',
            name='items',
            field=models.JSONField(default=list, verbose_name='موارد بسته بندی'),
        ),
    ]
