# Generated by Django 5.2 on 2025-06-22 22:41

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anbar', '0008_anbarrequestmodel_request_choice'),
        ('user', '0006_destinationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('approved', 'تأیید شده'), ('shipped', 'ارسال شده'), ('received', 'دریافت شده'), ('cancelled', 'لغو شده')], default='draft', max_length=50, verbose_name='وضعیت سفارش')),
                ('create_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سفارش خرید',
                'verbose_name_plural': 'سفارش\u200cهای خرید',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='شماره فاکتور')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.purchaseorder', verbose_name='سفارش خرید')),
            ],
            options={
                'verbose_name': 'فاکتور خرید',
                'verbose_name_plural': 'فاکتورهای خرید',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(auto_now_add=True, verbose_name='تاریخ دریافت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.purchaseorder', verbose_name='سفارش خرید')),
            ],
            options={
                'verbose_name': 'رسید کالا',
                'verbose_name_plural': 'رسیدهای کالا',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان درخواست')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('review_comment', models.TextField(blank=True, null=True, verbose_name='یادداشت مدیر')),
                ('create_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.personelmodel', verbose_name='درخواست\u200cدهنده')),
            ],
            options={
                'verbose_name': 'درخواست خرید',
                'verbose_name_plural': 'درخواست\u200cهای خرید',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='purchase_requests/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='business.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.anbarmodel', verbose_name='کالای درخواستی')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business.purchaserequest', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'آیتم درخواست خرید',
                'verbose_name_plural': 'آیتم\u200cهای درخواست خرید',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.FloatField(verbose_name='قیمت واحد')),
                ('create_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbar.anbarmodel', verbose_name='کالای سفارش\u200cداده\u200cشده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business.purchaseorder', verbose_name='سفارش')),
                ('request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.purchaserequestitem', verbose_name='آیتم درخواست مرتبط')),
            ],
            options={
                'verbose_name': 'آیتم سفارش خرید',
                'verbose_name_plural': 'آیتم\u200cهای سفارش خرید',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='user.citymodel', verbose_name='شهرستان')),
                ('ostan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ostan', to='user.ostanmodel', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'تأمین\u200cکننده',
                'verbose_name_plural': 'تأمین\u200cکنندگان',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.vendor', verbose_name='تأمین\u200cکننده'),
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام کامل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='سمت')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='business.vendor')),
            ],
            options={
                'verbose_name': 'شخص تماس',
                'verbose_name_plural': 'افراد تماس',
            },
        ),
    ]
