# Generated by Django 5.2 on 2025-06-23 00:05

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('editing', 'ویرایش بشه'), ('approved', 'تأیید شده'), ('shipped', 'ارسال شده'), ('received', 'دریافت شده'), ('cancelled', 'لغو شده')], default='draft', max_length=50, verbose_name='وضعیت سفارش'),
        ),
    ]
