# Generated by Django 5.2 on 2025-06-23 00:53

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_goodsreceipt_received_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestattachment',
            name='uploaded_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
