# Generated by Django 5.2 on 2025-04-06 14:16

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('gender', models.CharField(choices=[('M', 'پسر'), ('W', 'دختر')], max_length=2, verbose_name='نوع فرزند')),
                ('birthday', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تولد')),
            ],
            options={
                'verbose_name': 'فرزند',
                'verbose_name_plural': 'فرزند',
            },
        ),
        migrations.CreateModel(
            name='OstanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان',
            },
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'واحد',
                'verbose_name_plural': 'واحد',
            },
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='شهرستان')),
                ('ostan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ostanmodel', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'شهرستان',
                'verbose_name_plural': 'شهرستان',
            },
        ),
        migrations.CreateModel(
            name='PersonelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_code', models.CharField(max_length=10, verbose_name='شماره پرسنلی')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('date_employ', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ استخدام ')),
                ('work_type', models.CharField(max_length=50, verbose_name='عنوان شغلی')),
                ('post_work', models.CharField(max_length=50, verbose_name='پست شغلی')),
                ('shift', models.CharField(choices=[('R', 'روزکار'), ('SH', 'عصر و شب'), ('A', 'شیفت A'), ('B', 'شیفت B'), ('C', 'شیفت C'), ('D', 'شیفت D')], max_length=2, verbose_name='شیفت')),
                ('is_online', models.CharField(choices=[('A', 'فعال'), ('MA', 'مامور'), ('MO', 'مشاوره')], max_length=2, verbose_name='نحوه کار با شرکت')),
                ('is_active', models.BooleanField(default=True, verbose_name='آیا فعال است ؟')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('melli_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('sh_code', models.CharField(max_length=10, verbose_name='شماره شناسنامه')),
                ('sh_s_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره سریال شناسنامه')),
                ('father_name', models.CharField(max_length=50, verbose_name='نام پدر')),
                ('birthday', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد ')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('W', 'زن')], max_length=2, verbose_name='جنسیت')),
                ('solder_select', models.CharField(choices=[('P', 'پایان خدمت'), ('M', 'معافیت')], max_length=2, verbose_name='وضعیت نظام وظیفه')),
                ('reason_ex', models.CharField(blank=True, max_length=50, null=True, verbose_name='دلیل معافیت')),
                ('education', models.CharField(choices=[('DE', 'ابتدایی'), ('DR', 'راهنمایی'), ('DS', 'سیکل'), ('DD', 'دبیرستان'), ('DI', 'دیپلم'), ('FD', 'کاردانی'), ('LI', 'کارشناسی'), ('FL', 'کارشناسی ارشد'), ('PD', 'دکترا'), ('DA', 'دانشجو')], max_length=50, verbose_name='آخرین مدرک تحصیلی')),
                ('education_field', models.CharField(blank=True, max_length=50, null=True, verbose_name='رشته تحصیلی')),
                ('univercity', models.CharField(blank=True, max_length=50, null=True, verbose_name='دانشگاه')),
                ('Institute', models.CharField(blank=True, max_length=50, null=True, verbose_name='موسسه')),
                ('ev_file', models.BooleanField(default=False, verbose_name='مدرک در پرونده')),
                ('is_marid', models.BooleanField(default=True, verbose_name='وضعیت تاهل')),
                ('wife_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام همسر')),
                ('wife_birthday', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد همسر')),
                ('child_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد فرزند')),
                ('boy_child_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد فرزند پسر')),
                ('girl_child_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد فرزند دختر')),
                ('insurance_number', models.CharField(max_length=15, verbose_name='شماره بیمه')),
                ('insurance_history_day', models.CharField(max_length=15, verbose_name='سابقه بیمه قبل استخدام(روز)')),
                ('insurance_history_year', models.CharField(max_length=15, verbose_name='سابقه بیمه قبل استخدام(سال)')),
                ('bank_number', models.CharField(max_length=20, verbose_name='شماره حساب')),
                ('bank_shaba', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره شبا')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('post_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پستی')),
                ('settlement_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تسویه')),
                ('settlement_description', models.TextField(blank=True, null=True, verbose_name='دلیل تسویه')),
                ('sample_worker_month', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='ماه اعلام کارگر نمونه')),
                ('settlement_steps', models.BooleanField(default=False, verbose_name='در حال تصفیه')),
                ('sh_serial', models.CharField(max_length=10, verbose_name='سریال شناسنامه')),
                ('issue_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('married_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ عقد')),
                ('create_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('burn_ostan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burn_ostan', to='user.citymodel', verbose_name='محل صدور')),
                ('child', models.ManyToManyField(blank=True, null=True, to='user.childmodel', verbose_name='فرزند')),
                ('sh_ostan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sh_ostan', to='user.ostanmodel', verbose_name='استان محل تولد')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.unitmodel', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
            },
        ),
    ]
