# Generated by Django 5.2 on 2025-04-06 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostWorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='پست شغلی')),
            ],
            options={
                'verbose_name': 'پست شغلی',
                'verbose_name_plural': 'پست شغلی',
            },
        ),
        migrations.CreateModel(
            name='WorkTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='عنوان شغلی')),
            ],
            options={
                'verbose_name': 'عنوان شغلی',
                'verbose_name_plural': 'عنوان شغلی',
            },
        ),
        migrations.RemoveField(
            model_name='personelmodel',
            name='sample_worker_month',
        ),
        migrations.RemoveField(
            model_name='personelmodel',
            name='sh_serial',
        ),
        migrations.AlterField(
            model_name='personelmodel',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='personelmodel',
            name='bank_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='personelmodel',
            name='ev_file',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='مدرک در پرونده'),
        ),
        migrations.AlterField(
            model_name='personelmodel',
            name='insurance_history_day',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='سابقه بیمه قبل استخدام(روز)'),
        ),
        migrations.AlterField(
            model_name='personelmodel',
            name='insurance_history_year',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='سابقه بیمه قبل استخدام(سال)'),
        ),
        migrations.AlterField(
            model_name='personelmodel',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره بیمه'),
        ),
        migrations.AlterField(
            model_name='personelmodel',
            name='sh_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='personelmodel',
            name='solder_select',
            field=models.CharField(blank=True, choices=[('P', 'پایان خدمت'), ('M', 'معافیت')], max_length=2, null=True, verbose_name='وضعیت نظام وظیفه'),
        ),
        migrations.AlterField(
            model_name='personelmodel',
            name='post_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.postworkmodel', verbose_name='پست شغلی'),
        ),
        migrations.AlterField(
            model_name='personelmodel',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.worktypemodel', verbose_name='عنوان شغلی'),
        ),
    ]
