# Generated by Django 5.2 on 2025-04-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_postworkmodel_worktypemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelmodel',
            name='password',
            field=models.CharField(default=1, max_length=50, verbose_name='رمز عبور'),
            preserve_default=False,
        ),
    ]
