# Generated by Django 5.2 on 2025-04-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_personelmodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelmodel',
            name='access',
            field=models.CharField(choices=[('US', 'کارمند'), ('KA', 'کارگزینی'), ('HE', 'حسابداری'), ('AN', 'انبار'), ('MO', 'مدیریت'), ('NE', 'نگهبانی'), ('BA', 'بازرگانی')], default='US', max_length=3, verbose_name='سطح دسترسی'),
        ),
    ]
