# Generated by Django 5.2 on 2025-04-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_personelmodel_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personelmodel',
            name='is_online',
            field=models.CharField(choices=[('A', 'فعال'), ('MA', 'مامور'), ('MO', 'مشاور')], max_length=2, verbose_name='نحوه کار با شرکت'),
        ),
        migrations.AlterField(
            model_name='personelmodel',
            name='shift',
            field=models.CharField(choices=[('R', 'روزکار'), ('SH', 'عصر و شب')], max_length=2, verbose_name='شیفت'),
        ),
    ]
