# Generated by Django 5.2 on 2025-05-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_personelmodel_is_online_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('address', models.TextField(verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'مشتریان',
                'verbose_name_plural': 'مشتریان',
            },
        ),
    ]
