# Generated by Django 5.2 on 2025-04-18 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KalaGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='گروه کالا')),
            ],
            options={
                'verbose_name': 'گروه کالا',
                'verbose_name_plural': 'گروه کالا',
            },
        ),
        migrations.CreateModel(
            name='SellGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='گروه فروش')),
            ],
            options={
                'verbose_name': 'گروه فروش',
                'verbose_name_plural': 'گروه فروش',
            },
        ),
        migrations.CreateModel(
            name='ShopGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='گروه خريد')),
            ],
            options={
                'verbose_name': 'گروه خريد',
                'verbose_name_plural': 'گروه خريد',
            },
        ),
        migrations.CreateModel(
            name='AnbarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='کد کالا')),
                ('name', models.CharField(max_length=50, verbose_name='نام انبار')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcodes/', verbose_name='بارکد')),
                ('barcode_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='مسیر بارکد')),
                ('iran_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='ايران كد كالا')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('Inventory', models.CharField(default=0, max_length=50, verbose_name='موجودی')),
                ('min_Inventory', models.CharField(default=0, max_length=50, verbose_name='حداقل موجودي')),
                ('max_Inventory', models.CharField(default=0, max_length=50, verbose_name='حداكثر موجودي')),
                ('unit_type', models.CharField(choices=[('A', 'عدد'), ('KG', 'كيلوگرم'), ('GE', 'گرم'), ('LI', 'لیتر'), ('GA', 'گالن')], max_length=2, verbose_name='واحد اصلي')),
                ('sub_unit_type', models.CharField(choices=[('KI', 'كيسه'), ('KA', 'كارتن'), ('KG', 'كيلوگرم'), ('GA', 'گالن'), ('BA', 'بسته')], max_length=2, verbose_name='واحد فرعی')),
                ('kala_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anbar.kalagroupmodel', verbose_name='گروه کالا')),
                ('sell_groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anbar.sellgroupmodel', verbose_name='گروه فروش')),
                ('shop_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anbar.shopgroupmodel', verbose_name='گروه خريد')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبار',
            },
        ),
    ]
