# Generated by Django 5.2 on 2025-04-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anbarmodel',
            name='tag',
            field=models.CharField(choices=[('A', 'انبار اجناس'), ('K', 'انبار مواد')], default=1, max_length=2, verbose_name='تگ'),
            preserve_default=False,
        ),
    ]
