# Generated by Django 5.2 on 2025-04-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0002_anbarmodel_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anbarmodel',
            name='kala_group',
        ),
        migrations.RemoveField(
            model_name='anbarmodel',
            name='sell_groupe',
        ),
        migrations.RemoveField(
            model_name='anbarmodel',
            name='shop_group',
        ),
        migrations.DeleteModel(
            name='KalaGroupModel',
        ),
        migrations.DeleteModel(
            name='SellGroupModel',
        ),
        migrations.DeleteModel(
            name='ShopGroupModel',
        ),
    ]
