# Generated by Django 5.2 on 2025-04-23 20:50

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0003_remove_anbarmodel_kala_group_and_more'),
        ('user', '0005_alter_personelmodel_is_online_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnbarRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kala', models.JSONField(default=list, verbose_name='کالا ها')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات/دلیل درخواست')),
                ('status', models.CharField(choices=[('P', 'در انتظار بررسی'), ('A', 'تایید شده'), ('R', 'رد شده'), ('C', 'تکمیل شده')], default='P', max_length=1, verbose_name='وضعیت درخواست')),
                ('approved_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تایید/رد')),
                ('create_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='user.personelmodel', verbose_name='تایید کننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.personelmodel', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست کالا',
                'verbose_name_plural': 'درخواست کالا',
                'ordering': ['-create_at'],
            },
        ),
    ]
