# Generated by Django 5.2 on 2025-05-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0004_anbarrequestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anbarrequestmodel',
            name='status',
            field=models.CharField(choices=[('P', 'در انتظار بررسی'), ('A', 'تایید شده'), ('R', 'رد شده'), ('C', 'تکمیل شده'), ('U', 'لغو شده')], default='P', max_length=1, verbose_name='وضعیت درخواست'),
        ),
    ]
