# Generated by Django 5.2 on 2025-05-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0005_alter_anbarrequestmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='anbarrequestmodel',
            name='unit_price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='قیمت هر واحد ماده اولیه'),
        ),
        migrations.AlterField(
            model_name='anbarmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام کالا'),
        ),
    ]
