# Generated by Django 5.2 on 2025-05-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0006_anbarrequestmodel_unit_price_alter_anbarmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anbarrequestmodel',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='anbarmodel',
            name='unit_price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='قیمت هر واحد ماده اولیه'),
        ),
    ]
