# Generated by Django 5.2 on 2025-06-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0007_remove_anbarrequestmodel_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anbarrequestmodel',
            name='request_choice',
            field=models.CharField(choices=[('A', 'درخواست کالا'), ('B', 'برگشت کالا')], default='A', max_length=1, verbose_name='نوع درخواست'),
        ),
    ]
